const L={puzzle:"загадка",diamond:"алмаз",star:"звезда",weak:"слабый",core:"ядро",ic:"сильный IC",out:"на выход",steady:"стабильный",expert:"эксперт"};
const G=[["puzzle","diamond","star"],["weak","core","ic"],["out","steady","expert"]];
const P={"demo-inc":{n:"Pavel Orlov",t:"Partner",b:"core"},"demo-star":{n:"Maria Iyer",t:"Lead",b:"star",w:"client 4.8"},"demo-expert":{n:"Dmitry Volkov",t:"Principal",b:"expert",w:"IC"},"demo-diamond":{n:"Ananya Reddy",t:"Tech Lead",b:"diamond",w:"P&L"},"demo-split":{n:"Kirill Novikov",t:"Lead",b:"star",w:"Healthcare",prim:"Healthcare"},"demo-hinc":{n:"Elena Sokolova",t:"Partner",b:"expert"}};
let S={role:"head",page:"p",m:"9",cand:"demo-star",pick:null,modal:null,person:null,roles:[
{id:"n",name:"DP — Nordics",inc:"demo-inc",pl:[],rec:["demo-star","demo-diamond","demo-expert","demo-split"],em:null,hz:{},dis:[],goals:{"demo-star":[{t:"QBR",due:"2026-10-15",s:"open",by:"head"}]}},
{id:"h",name:"DP — Healthcare",inc:"demo-hinc",pl:[{id:"demo-split",k:"primary"}],rec:[],em:null,hz:{"demo-split":"6m"},dis:[],goals:{"demo-split":[{t:"Shadow QBR",due:"2026-10-30",s:"open",by:"head"}]}}
]};
const C={head:{sl:1,ed:1,hz:1,go:1,box:0,cm:1},hr:{sl:0,ed:0,hz:0,go:0,box:1,cm:1},observer:{sl:0,ed:0,hz:0,go:0,box:0,cm:0},candidate:{sl:0,ed:0,hz:0,go:1,box:0,cm:0}};
const R=id=>S.roles.find(r=>r.id===id);
function rn(r){return r.pl.some(x=>(r.hz[x.id]||"")==="ready_now")}
function gs(r,id){r.goals[id]=r.goals[id]||[];return r.goals[id]}
function hdr(){
 document.body.className=S.role;
 document.getElementById("nav").innerHTML=S.role==="candidate"?"":`<button class="${S.page==="p"?"on":""}" onclick="S.page='p';draw()">Pipeline</button><button class="${S.page==="x"?"on":""}" onclick="S.page='x';draw()">Матрица</button>`;
 document.getElementById("sw").innerHTML=["observer","head","hr","candidate"].map(k=>`<button class="${S.role===k?"on":""}" onclick="S.role='${k}';S.modal=S.pick=S.person=null;draw()">${k}</button>`).join("")
 +(S.role==="candidate"?`<select onchange="S.cand=this.value;draw()">${Object.keys(P).map(id=>`<option value="${id}" ${id===S.cand?"selected":""}>${P[id].n}</option>`).join("")}</select>`:"");
 const a=S.roles.filter(r=>!rn(r)).length,b=S.roles.filter(r=>!r.pl.length).length,c=S.roles.filter(r=>!r.em).length;
 document.getElementById("cnt").textContent=S.role==="candidate"?"":`нет ready-now ${a} · без planned ${b} · нет cover ${c}`;
}
function addP(rid,pid){const r=R(rid);if(P[pid].prim&&P[pid].prim!==r.name){alert("bench горит");return;}if(r.pl.some(x=>x.id===pid))return;r.pl.push({id:pid,k:"backup"});r.rec=r.rec.filter(i=>i!==pid);if(!r.hz[pid])r.hz[pid]="12m";draw()}
function remP(rid,pid){const r=R(rid);r.pl=r.pl.filter(x=>x.id!==pid);delete r.hz[pid];if(!r.dis.includes(pid)&&!r.rec.includes(pid))r.rec.push(pid);draw()}
function remE(rid,pid){const r=R(rid);r.rec=r.rec.filter(i=>i!==pid);if(!r.dis.includes(pid))r.dis.push(pid);draw()}
function hz(rid,pid,v){const r=R(rid);r.hz[pid]=(v==="ready_now"&&r.hz[pid]==="ready_now")?"6m":v;draw()}
function row(id,r){return `<div><b onclick="openP('${id}','${r.id}')">${P[id].n}</b> <span class="chip">${r.hz[id]||"—"}</span> <span class="chip">${P[id].b}</span> <span class="why">${P[id].w||""}</span></div>`}
function btnsP(r,id){return `<div>${["ready_now","6m","12m","18m"].map(h=>`<button onclick="hz('${r.id}','${id}','${h}')">${h}</button>`).join("")}<button onclick="remP('${r.id}','${id}')">−</button></div>`}
function btnsR(r,id){return `<div><button onclick="addP('${r.id}','${id}')">в planned</button><button onclick="R('${r.id}').em='${id}';draw()">emergency</button>${["6m","12m","18m"].map(h=>`<button onclick="hz('${r.id}','${id}','${h}')">${h}</button>`).join("")}<button onclick="remE('${r.id}','${id}')">−</button></div>`}
function pipe(){const sl=C[S.role].sl;return `<div class="grid">${S.roles.map(r=>`<article class="card ${rn(r)?"":"risk"}"><h3>${r.name}</h3><div class="why">inc ${P[r.inc].n} · ${rn(r)?"ready-now":"нет ready-now"}</div><div class="why">PLANNED</div>${r.pl.map(x=>row(x.id,r)+(sl?btnsP(r,x.id):"")).join("")||"<div class='why'>пусто</div>"}<div class="why">RECOMMENDED</div>${r.rec.map(id=>row(id,r)+(sl?btnsR(r,id):"")).join("")}${sl?`<button onclick="S.modal={t:'pool',rid:'${r.id}'};draw()">+ из пула</button>`:""}${C[S.role].ed?`<button onclick="S.modal={t:'role',id:'${r.id}'};draw()">редактировать</button>`:""}<div class="why">Emergency: ${r.em?P[r.em].n:"—"} ${r.em&&sl?`<button onclick="R('${r.id}').em=null;draw()">снять</button>`:""}</div></article>`).join("")}</div>`+(C[S.role].ed?`<p style="padding:0 16px"><button class="acc" onclick="S.modal={t:'role'};draw()">Новая роль</button></p>`:"")}
function nine(){const ids=new Set();S.roles.forEach(r=>{[r.inc,...r.pl.map(x=>x.id),...r.rec,r.em].forEach(i=>i&&ids.add(i))});const by={};[...ids].forEach(id=>{(by[P[id].b]=by[P[id].b]||[]).push(id)});const box=C[S.role].box;let h=`<div class="how">9-box не оценка «хороший/плохой». Звезда/алмаз — planned. Эксперт — не partner. Клетка ≠ дата. ${box?"HR: клик → 9 клеток + коммент.":"Просмотр."} <button onclick="S.m='9';draw()">9-box</button> <button onclick="S.m='t';draw()">Таймлайн</button></div><div class="nine"><div></div><div class="why">low</div><div class="why">med</div><div class="why">high</div>`;[["hi",G[0]],["mid",G[1]],["lo",G[2]]].forEach(([lab,row])=>{h+=`<div class="why">${lab}</div>`;row.forEach(b=>{h+=`<div class="cell"><div class="why">${L[b]}</div>${(by[b]||[]).map(id=>`<button onclick="${box?`S.pick='${id}';draw()`:`openP('${id}')`}">${P[id].n}</button>`).join("")}</div>`})});return h+"</div>"+(S.pick&&box?`<div class="modal"><div class="box"><h3>${P[S.pick].n}</h3>${Object.keys(L).map(k=>`<label><input type="radio" name="bx" value="${k}" ${P[S.pick].b===k?"checked":""}/> ${L[k]}</label>`).join("")}<textarea id="note" placeholder="почему"></textarea><button onclick="S.pick=null;draw()">отмена</button><button class="acc" onclick="svBox()">ок</button></div></div>`:"")}
function svBox(){const n=document.getElementById("note").value.trim();if(!n){alert("нужен комментарий");return;}P[S.pick].b=[...document.querySelectorAll("[name=bx]")].find(i=>i.checked).value;S.pick=null;draw()}
function time(){const cols=["ready_now","6m","12m","18m"];let h=`<div class="how"><button onclick="S.m='9';draw()">9-box</button> Таймлайн: жирный = planned</div><table border=1 cellpadding=6 style="margin:16px;border-collapse:collapse"><tr><th>роль</th>${cols.map(c=>`<th>${c}</th>`).join("")}</tr>`;S.roles.forEach(r=>{h+=`<tr><td>${r.name}${rn(r)?"":" ✗"}</td>`;cols.forEach(c=>{const a=r.pl.filter(x=>(r.hz[x.id]||"")===c).map(x=>"<b>"+P[x.id].n+"</b>");const b=r.rec.filter(id=>(r.hz[id]||"")===c).map(id=>P[id].n);h+=`<td>${[...a,...b].join("<br>")||"—"}</td>`});h+="</tr>"});return h+"</table>"}
function mine(){const id=S.cand;const rs=S.roles.filter(r=>r.pl.some(x=>x.id===id)||r.rec.includes(id));return `<p class="how">Кабинет кандидата. Только свои роли.</p><h2 style="padding:0 16px">${P[id].n}</h2><div class="grid">${rs.map(r=>{const g=gs(r,id);return `<article class="card"><h3>${r.name}</h3><span class="chip">${r.pl.some(x=>x.id===id)?"planned":"recommended"}</span> <span class="chip">${r.hz[id]||"—"}</span>${g.map((x,i)=>`<div>${x.t} · ${x.due||"без даты"} · ${x.s} <button onclick="gs(R('${r.id}'),'${id}')[${i}].s='done';draw()">готово</button> <button onclick="S.modal={t:'goal',rid:'${r.id}',pid:'${id}',i:${i}};draw()">дата</button></div>`).join("")}<button class="acc" onclick="S.modal={t:'goal',rid:'${r.id}',pid:'${id}'};draw()">+ цель</button></article>`}).join("")||"<p>нет ролей</p>"}</div>`}
function openP(id,rid){S.person={id,rid};draw()}
function card(){if(!S.person||S.role==="candidate")return"";const p=P[S.person.id],r=R(S.person.rid)||S.roles[0],g=gs(r,S.person.id);return `<div class="modal" onclick="if(event.target===this){S.person=null;draw()}"><div class="box"><button onclick="S.person=null;draw()">закрыть</button><h3>${p.n}</h3><div class="why">${r.name} · ${p.b}</div>${g.map((x,i)=>`<div>${x.t} · ${x.due||"—"} · ${x.s} ${C[S.role].go?`<button onclick="gs(R('${r.id}'),'${S.person.id}').splice(${i},1);draw()">удалить</button>`:""}</div>`).join("")}${C[S.role].go?`<button class="acc" onclick="S.modal={t:'goal',rid:'${r.id}',pid:'${S.person.id}'};draw()">+ цель</button>`:""}${C[S.role].hz?["ready_now","6m","12m","18m"].map(h=>`<button onclick="hz('${r.id}','${S.person.id}','${h}')">${h}</button>`).join(""):""}${C[S.role].cm?`<textarea id="cmt" placeholder="коммент"></textarea>`:""}</div></div>`}
function mods(){if(!S.modal)return"";if(S.modal.t==="goal"){const g=S.modal.i!=null?gs(R(S.modal.rid),S.modal.pid)[S.modal.i]:null;return `<div class="modal"><div class="box"><h3>Цель</h3><input id="gt" value="${g?g.t:""}"/><input id="gd" type="date" value="${g?g.due:""}"/><button onclick="S.modal=null;draw()">нет</button><button class="acc" onclick="svG()">ок</button></div></div>`}if(S.modal.t==="pool"){return `<div class="modal"><div class="box"><h3>В recommended</h3><select id="pool">${Object.keys(P).map(id=>`<option value="${id}">${P[id].n}</option>`).join("")}</select><button onclick="S.modal=null;draw()">нет</button><button class="acc" onclick="const r=R(S.modal.rid),id=pool.value;if(!r.rec.includes(id)&&r.inc!==id){r.dis=r.dis.filter(i=>i!==id);r.rec.push(id)}S.modal=null;draw()">ок</button></div></div>`}if(S.modal.t==="role"){const r=S.modal.id?R(S.modal.id):null;return `<div class="modal"><div class="box"><h3>${r?"Редакт":"Новая"} роль</h3><input id="rn" value="${r?r.name:""}"/><select id="ri">${Object.keys(P).map(id=>`<option value="${id}">${P[id].n}</option>`).join("")}</select><button onclick="S.modal=null;draw()">нет</button><button class="acc" onclick="svR()">ок</button></div></div>`}return""}
function svG(){const t=gt.value.trim(),d=gd.value,m=S.modal;if(m.i!=null){const g=gs(R(m.rid),m.pid)[m.i];g.t=t||g.t;g.due=d}else gs(R(m.rid),m.pid).push({t:t||"Цель",due:d,s:"open",by:S.role});S.modal=null;draw()}
function svR(){const name=rn.value||"Роль",inc=ri.value;if(S.modal.id){const r=R(S.modal.id);r.name=name;r.inc=inc;r.pl=r.pl.filter(x=>x.id!==inc);r.rec=r.rec.filter(i=>i!==inc)}else S.roles.unshift({id:"r"+Date.now(),name,inc,pl:[],rec:["demo-star"],em:null,hz:{},dis:[],goals:{}});S.modal=null;draw()}
function draw(){hdr();document.getElementById("app").innerHTML=(S.role==="candidate"?mine():S.page==="p"?pipe():S.m==="t"?time():nine())+card()+mods()}
draw();
